local_configs:
  "claude code": "CLAUDE.md"
  codex: "AGENTS.md"
  windsurf: ".windsurfrules"

global_configs:
  "claude code": "~/.claude/CLAUDE.md"
  codex: "~/.codex/AGENTS.md"
  windsurf: "~/.codeium/windsurf/memories/global_rules.md"

gent_dirs:
  local: ".gent/rules.md"
  global: "~/.config/gent/rules.md"

mcp_configs:
  "claude code": "~/.claude.json"

gent_mcp_dirs:
  local: ".gent/mcp.yaml"
  global: "~/.config/gent/mcp.yaml"
